In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
DATA_PATH = Path("../data/final/dataset_maitre_trends_tourisme_afrique.csv")

df = pd.read_csv(DATA_PATH)

df.head()

,dataset_layer,destination,iso3,year,origin_name,origin_region,granularity,metric,value,unit,metric_type,coverage_scope,source_name,source_reference,source_file,quality_flag,notes
0,arrivals,Afrique du Sud,ZAF,1995,NaN,NaN,destination_total,tourist_arrivals,4684000.0,persons,destination_total,Common WDI destination-level series,World Bank WDI,WB_WDI_ST_INT_ARVL,audit_harmonisation_arrivees_7_pays_trends.xlsx,available,No interpolation; missing stays blank.
1,arrivals,Afrique du Sud,ZAF,1996,NaN,NaN,destination_total,tourist_arrivals,5186000.0,persons,destination_total,Common WDI destination-level series,World Bank WDI,WB_WDI_ST_INT_ARVL,audit_harmonisation_arrivees_7_pays_trends.xlsx,available,No interpolation; missing stays blank.
2,arrivals,Afrique du Sud,ZAF,1997,NaN,NaN,destination_total,tourist_arrivals,5170000.0,persons,destination_total,Common WDI destination-level series,World Bank WDI,WB_WDI_ST_INT_ARVL,audit_harmonisation_arrivees_7_pays_trends.xlsx,available,No interpolation; missing stays blank.
3,arrivals,Afrique du Sud,ZAF,1998,NaN,NaN,destination_total,tourist_arrivals,5898000.0,persons,destination_total,Common WDI destination-level series,World Bank WDI,WB_WDI_ST_INT_ARVL,audit_harmonisation_arrivees_7_pays_trends.xlsx,available,No interpolation; missing stays blank.
4,arrivals,Afrique du Sud,ZAF,1999,NaN,NaN,destination_total,tourist_arrivals,6026000.0,persons,destination_total,Common WDI destination-level series,World Bank WDI,WB_WDI_ST_INT_ARVL,audit_harmonisation_arrivees_7_pays_trends.xlsx,available,No interpolation; missing stays blank.

In [3]:
print("Dimensions :", df.shape)
print("\nColonnes :")
print(df.columns.tolist())

print("\nTypes de données :")
print(df.dtypes)

Dimensions : (1080, 17)

Colonnes :
['dataset_layer', 'destination', 'iso3', 'year', 'origin_name', 'origin_region', 'granularity', 'metric', 'value', 'unit', 'metric_type', 'coverage_scope', 'source_name', 'source_reference', 'source_file', 'quality_flag', 'notes']

Types de données :
dataset_layer        object
destination          object
iso3                 object
year                  int64
origin_name          object
origin_region        object
granularity          object
metric               object
value               float64
unit                 object
metric_type          object
coverage_scope       object
source_name          object
source_reference     object
source_file          object
quality_flag         object
notes                object
dtype: object

##  Contrôle qualité et couverture des données

Avant de commencer l'analyse statistique, il est nécessaire de vérifier la structure et la couverture du dataset maître.

Cette étape permet notamment de :

- contrôler le nombre d'observations disponibles pour chaque destination ;
- distinguer les différentes couches de données : arrivées, recettes et provenance ;
- identifier les valeurs manquantes ;
- vérifier les périodes couvertes par les différentes sources ;
- éviter de comparer des données dont les périmètres ou les périodes ne sont pas compatibles.

Les valeurs manquantes sont conservées comme telles et ne sont pas remplacées automatiquement par zéro, conformément aux règles d'harmonisation définies lors de la préparation des données.

In [4]:
print("Valeurs manquantes :")
print(df.isna().sum())

print("\nPays présents :")
print(df["destination"].unique())

print("\nCouches de données :")
print(df["dataset_layer"].value_counts())

Valeurs manquantes :
dataset_layer         0
destination           0
iso3                  0
year                  0
origin_name         364
origin_region       364
granularity           0
metric                0
value                67
unit                  0
metric_type           0
coverage_scope        0
source_name           0
source_reference      0
source_file           0
quality_flag          0
notes                 0
dtype: int64

Pays présents :
['Afrique du Sud' 'Égypte' 'Maurice' 'Tanzanie' 'Tunisie' 'Maroc' 'Kenya']

Couches de données :
dataset_layer
provenance    716
arrivals      182
receipts      182
Name: count, dtype: int64

### Interprétation des valeurs manquantes

La présence de valeurs manquantes ne signifie pas que la valeur observée est égale à zéro.

Elle indique qu'aucune valeur compatible n'était disponible dans la source utilisée pour l'année et l'indicateur concernés.

Afin de préserver la qualité des données, aucune interpolation ou extrapolation automatique n'est réalisée à ce stade.

Cette distinction est particulièrement importante pour éviter de sous-estimer artificiellement les arrivées ou les recettes touristiques.

In [5]:
# Répartition des observations par pays et par couche de données

observations_par_pays = pd.crosstab(
    df["destination"],
    df["dataset_layer"]
)

observations_par_pays

dataset_layer   arrivals  provenance  receipts
destination
Afrique du Sud        26          54        26
Kenya                 26          90        26
Maroc                 26         117        26
Maurice               26          21        26
Tanzanie              26          45        26
Tunisie               26         371        26
Égypte                26          18        26

### Lecture du tableau

Ce tableau présente le nombre d'observations disponibles pour chaque destination et pour chaque couche du dataset.

Les couches `arrivals` et `receipts` présentent une structure relativement homogène car elles proviennent principalement d'une source commune, la Banque mondiale (WDI).

La couche `provenance` est davantage hétérogène. Le nombre d'observations varie selon les pays en raison des différences de période, de niveau de détail et de couverture des sources nationales.

Cette différence devra être prise en compte lors des comparaisons entre marchés d'origine.

In [6]:
# Nombre de valeurs disponibles et manquantes par couche

controle_valeurs = (
    df.groupby("dataset_layer")["value"]
      .agg(
          observations="size",
          valeurs_disponibles="count",
          valeurs_manquantes=lambda x: x.isna().sum()
      )
)

controle_valeurs

               observations  valeurs_disponibles  valeurs_manquantes
dataset_layer
arrivals                182                  179                   3
provenance              716                  656                  60
receipts                182                  178                   4

In [7]:
# Période couverte par pays et par couche de données

couverture_temporelle = (
    df.groupby(["destination", "dataset_layer"])
      .agg(
          annee_debut=("year", "min"),
          annee_fin=("year", "max"),
          observations=("year", "size")
      )
      .reset_index()
)

couverture_temporelle

       destination dataset_layer  annee_debut  annee_fin  observations
0   Afrique du Sud      arrivals         1995       2020            26
1   Afrique du Sud    provenance         2022       2024            54
2   Afrique du Sud      receipts         1995       2020            26
3            Kenya      arrivals         1995       2020            26
4            Kenya    provenance         2022       2024            90
5            Kenya      receipts         1995       2020            26
6            Maroc      arrivals         1995       2020            26
7            Maroc    provenance         2012       2020           117
8            Maroc      receipts         1995       2020            26
9          Maurice      arrivals         1995       2020            26
10         Maurice    provenance         2022       2024            21
11         Maurice      receipts         1995       2020            26
12        Tanzanie      arrivals         1995       2020            26
13        Tanzanie    provenance         2022       2024            45
14        Tanzanie      receipts         1995       2020            26
15         Tunisie      arrivals         1995       2020            26
16         Tunisie    provenance         2017       2023           371
17         Tunisie      receipts         1995       2020            26
18          Égypte      arrivals         1995       2020            26
19          Égypte    provenance         2010       2019            18
20          Égypte      receipts         1995       2020            26

### Lecture de la couverture temporelle

La couverture temporelle n'est pas identique pour toutes les couches du dataset.

Les séries d'arrivées et de recettes permettent une analyse historique relativement longue et comparable entre plusieurs destinations.

En revanche, les données de provenance proviennent principalement de sources statistiques nationales. Leur période de disponibilité et leur niveau de détail diffèrent donc selon les pays.

Par conséquent, les analyses de provenance seront réalisées en tenant compte du périmètre propre à chaque source. Une absence de donnée ne sera jamais interprétée comme une absence de touristes provenant du marché concerné.